[package]
name = "wasm_runtime_layer"
version = "0.1.4"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DouglasDwyer/wasm_runtime_layer"
readme = "README.md"
description = """
Compatibility interface for WASM runtimes.
"""

[dependencies]
anyhow = { version = "1.0.71", default-features = false, features = [ "std" ] }
fxhash = { version = "0.2.1", default-features = false }
ref-cast = { version = "1.0.19", default-features = false }
smallvec = { version = "1.11.0", default-features = false }

wasmi = { version = ">=0.0.0", optional = true, default-features = false, features = [ "std" ] }
wasmtime = { version = ">=0.0.0", optional = true, default-features = false, features = [ "cranelift" ] }
tracing = { version = "0.1", optional = true }
slab = { version = "0.4", optional = true }

wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
web-sys = { version = "0.3", features = ["Clipboard"], optional = true }
wasmparser = { version = "0.118", default-features = false, optional = true }

[dev-dependencies]
wat = "1.0"
wasm-bindgen-test = "0.3"
# wasm_runtime_layer = { path = ".", features = [ "backend_wasmi" ] }

[features]
backend_wasmi = [ "wasmi" ]
backend_wasmtime = [ "wasmtime" ]
backend_web = [ "wasm-bindgen", "js-sys", "web-sys", "tracing", "slab", "wasmparser" ]

[package.metadata."docs.rs"]
all-features = true
