[package]
name = "wasm_runtime_layer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
ref-cast = "1.0.19"
smallvec = "1.11.0"

wasmi = { version = "0.31.0", optional = true }

[features]
default = [ "backend_wasmi" ]
backend_wasmi = [ "wasmi" ]