[package]
name = "wasm_runtime_layer"
version = "0.1.4"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DouglasDwyer/wasm_runtime_layer"
readme = "README.md"
description = """
Compatibility interface for WASM runtimes.
"""

[dependencies]
anyhow = { version = "1.0.71", default-features = false, features = [ "std" ] }
fxhash = { version = "0.2.1", default-features = false }
ref-cast = { version = "1.0.19", default-features = false }
smallvec = { version = "1.11.0", default-features = false }

wasmi = { version = "*", optional = true, default-features = false, features = [ "std" ] }
wasmtime = { version = "*", optional = true, default-features = false, features = [ "cranelift" ] }

[dev-dependencies]
wabt = "0.10.0"
wasm_runtime_layer = { path = ".", features = [ "backend_wasmi" ] }

[features]
backend_wasmi = [ "wasmi" ]
backend_wasmtime = [ "wasmtime" ]